### ISSUE TITLE
Symbol annotation does not seem to take point.value

### ISSUE THREAD

**Issue by fuzzthink** [liihuu/KLineChart#195]
Seems like if I want to create a simple annotation using existing symbol types like 'circle', it will only render at top of the chart even if `value` (tried `price` too) is passed. Seems like the value is ignored. If this is true, why? It is useful to be able to draw simple predefined shapes anywhere w/o defining drawExtend.

**Comment by fuzzthink** [comment]
Hmm, I think I understand now that annotations are for rendering at static y-positions. To render simple shapes that moves along with the chart, shapes are needed.

**Comment by liihuu** [comment]
Shapes are generally used for multiple points, while annotations are used for single points.

**Comment by fuzzthink** [comment]
I think ability to specify the `y` value via `point.value` is still useful for single point annotations. Without it, one will need to resort to shapes.

**Comment by e0** [comment]
I was looking into this as well and saw that this issue is already resolved. It took me a while to find out the solution after digging into the [code](https://github.com/liihuu/KLineChart/blob/7d3c4eb5fb8cb96c81b839032d56c0a1f7da9c60/src/component/overlay/Annotation.js#L111-L115).

For anyone else that runs into this, you need to set the `position` to `point`. For example:

```javascript
chart.createAnnotation({
  point: { timestamp: 1657742400000, value: 100 },
  styles: {
    position: 'point',
    ...
```
