### ISSUE TITLE
[Bug] Trying to get in touch with you LIHU

### ISSUE THREAD

**Issue by angadgocharting** [liihuu/KLineChart#319]
### Version

1

### Steps to Reproduce

Hey, hi Lihu, hope you are fine this is GoCharting. 
Are you available for a quick call with us?
Been trying to get in touch with you after we last spoke. 
hope all is well. 

### Current Behavior

1

### Expected Behavior

1

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by gldstrrbt** [comment]
@angadgocharting how about you _go_ maintain/fully document your react stockcharts library instead of trying to quell the potential of having private and/or os competition?

**Comment by gocharting101** [comment]
> @angadgocharting how about you _go_ maintain/fully document your react stockcharts library instead of trying to quell the potential of having private and/or os competition?

Firstly who are you and why this irrelevant comment when you dont know the context?  When two open-sourcing project contributors are trying to collaborate on another open-source project, what value are you adding with such comments?  It will add immense value to the dev community as we see it.  So unless you have something constructive to add to the open-source community, suggest you stay out of it.

**Comment by gldstrrbt** [comment]
@angadgocharting

> 	why this irrelevant comment when you don't know the context?

Not irrelevant. These inquiries of yours (a private entity -> gocharting.com / gocharting app), requesting private communications in this repo's issues, in combination with the years long abandonment of react-stockcharts, gives off the sense of an anti-competitive agenda.

>  (which from your profile is clear that your own contribution has been minimal)

As is clear from your profile as well.

> 	When two open-sourcing project contributors are trying to collaborate on another open-source project, what value are you adding with such comments? It will add immense value to the dev community as we see it. So unless you have something constructive to add to the open-source community

Then why not openly post your inquiries for all to see in the dev community, rather than in private? Can we know how this potential collaboration would benefit the dev community? What's this "immense" value you speak of that cannot be posted publicly? 

Is this about the "dev" community or the open source community? Your use of the term "dev community" is vague and could very well be interpreted as "a private api and/or library that gocharting and/or <insert private entity and/or partnership> offers to developers at a cost".

It's suspicious considering that you're reaching out to the dev of a charting library which trumps react-stockcharts in base quality, interactivity, performance, etc, and enables others to compete against the business interests, revenue, and market share of gocharting.com and the gocharting app. Not to mention the lack of documenting and maintaining of the react-stockcharts repo ever since pivoting to focus on private endeavors. Why jump back into (supposedly) contributing to open source charting/TA projects now, when that could have been done in the years since abandoning react-stockcharts?

In addition to your lack of transparency, your motives are questionable seeing that you're using a handle that is in reference to your private business rather than @rrag or an account related to @rrag / react-stockcharts. Years of radio silence from @rrag, but now there's activity from an account whose name references his private business and appears to only be used to reach out to projects which compete with their business's interests/bottom line? 

Sorry, but that's sus and infuriating to think that it could be an attempt to disrupt the development of this awesome project many seem to be flocking to.
