### ISSUE TITLE
Has crossed a line from GraphicMark

### ISSUE THREAD

**Issue by danielmalencar** [liihuu/KLineChart#98]
Hello!
I need to know if a value has crossed a line from GraphicMark. How should I do?
Thanks!

**Comment by danielmalencar** [comment]
Any idea, please?

**Comment by liihuu** [comment]
Can't do it now.🙁

**Comment by danielmalencar** [comment]
I can, but I need to access this information as a property of GraphicMark. With them it is possible to make the calculation!
[image](https://user-images.githubusercontent.com/25048796/113050884-be9e9180-917b-11eb-8c64-6b3bc702a304.png)

**Comment by fuzzthink** [comment]
The solution for a rayLine is pretty simple, with some assumptions.

If we can assume the 2 points are drawn far apart, and there aren't much gaps between the 2nd mark and the new bar you are trying to determine, then we do not need to involve the actual x/y pixels. The result is pretty accurate for a few lines I drew. 

This not only simplifies the calculation, but is a necessity if one needs the marks to signal alerts since you don't want to have to render all symbols and marks in order for the alerts to be determined.

```javascript
/**
 * @param {timestamp: Integer, price: Number} p1, p2
 * @returns {k: Number, b: Number} where k is the slop and b is the price intercept
 */
const getSlopeIntercept = (p1={}, p2={}) => {
  const tsDiff = p1.timestamp - p2.timestamp
  if (!tsDiff) 
    return {}
  const k = (p1.price - p2.price) / tsDiff
  return {
    k,
    b: p1.price - k * p1.timestamp,
  }
}

export const getPriceAt = (timestamp=0, p1={}, p2={}) => {
  const { k, b } = getSlopeIntercept(p1, p2)
  return k ? k*timestamp + b : NaN
} 
```

@liihuu General coding thought. I think functions should conform to an interface, returning the same type in all cases (and throws error when it should). For example, `getLinearSlopeIntercept` should return an empty object even if x-diff is zero. This way, usage can always assume the result is an object and check the properties instead of the returned result instead. This gives you some of the benefits of a typed language like typescript w/o actually using it.

**Comment by liihuu** [comment]
Version 7.1.0 can add onMouseEnter and onMouseLeave events to graphic markers.
